# Add this snippet to the top of your playbook. 
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  
  tasks:
  - name: Check if i386 is enabled
    become: yes
    shell: dpkg --print-foreign-architectures | grep i386
    register: result_i386_check
    changed_when: result_i386_check.rc == 1
    failed_when: result_i386_check.rc > 1

  - name: Enable i386 architecture
    become: yes
    command: dpkg --add-architecture i386
    when: result_i386_check.rc == 1

  - name: Ensure apt cache is up to date
    become: yes
    apt: update_cache=yes
    when: result_i386_check.rc == 1

  - name: Ensure that sudo is installed
    become: yes
    apt: 
      name: sudo

  - name: Ensure sudo doesnt require a password
    become: yes
    lineinfile:   
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: "Add the user {{ item }} with a bash shell, appending the group sudo to the user's groups"
    become: yes
    user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: sudo
      append: yes
    with_items:
      - arma
      - teamspeak
      - minecraft
      
  - name: "Ensure ssh dir exists for {{ item }}"
    become: yes
    file:
      path: "/home/{{ item }}/.ssh"
      state: directory
      owner: "{{ item }}"
    with_items:
      - arma
      - teamspeak
      - minecraft

  - name: "Set authorized key for {{ item }} taken from root"
    become: yes
    copy:
      src: /home/ubuntu/.ssh/authorized_keys
      dest: "/home/{{ item }}/.ssh/authorized_keys"
      remote_src: yes
    with_items:
      - arma
      - teamspeak
      - minecraft