---
- hosts: game
  remote_user: teamspeak
  tasks:

  - name: Install TS3 requirements
    become: yes 
    apt: 
      name: "{{ packages }}"
      update_cache: yes
    vars: 
      packages:
      - mailutils 
      - postfix 
      - curl 
      - wget 
      - file 
      - bzip2 
      - gzip 
      - unzip 
      - bsdmainutils 
      - python 
      - util-linux 
      - ca-certificates 
      - binutils 
      - bc 
      - jq 
      - mariadb-common

  - name: Download linuxgsm installer
    get_url:
      url: https://linuxgsm.sh
      dest: /home/teamspeak/linuxgsm.sh
      mode: 0755

  - name: Install linuxgsm
    command: /home/teamspeak/linuxgsm.sh ts3server
    args:
      chdir: /home/teamspeak
      creates: /home/teamspeak/ts3server

  - name: Install TS3
    command: /home/teamspeak/ts3server ai
    args:
      chdir: /home/teamspeak
      creates: /home/teamspeak/serverfiles

  - name: Start TS3
    command: /home/teamspeak/ts3server start
    args:
      chdir: /home/teamspeak
    ignore_errors: true

  - name: Create TS3 Service
    become: yes
    copy:
      src: systemd.service
      dest: /etc/systemd/system/teamspeak3.service
      mode: 0666

  - name: Start and enable TS3 service
    become: yes
    systemd:
      state: restarted
      daemon_reload: yes
      name: teamspeak3.service

  - name: Enable Services
    become: yes
    systemd:
      enabled: yes
      name: "{{ services }}"
    vars:
      services:
        - teamspeak3
