version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu18.04

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:56:ed:db:cc:77:03:e3:95:51:05:ed:69:f3:2e:9e"
      - checkout

      - run:
          name: Chmod .vault_pass.py
          command: chmod 0755 .vault_pass.py

      - run:
          name: Provision the server
          command: ansible-playbook -vvvv -i ./hosts Global/initial.yml Arma/server.yml Teamspeak/server.yml Minecraft/server.yml --vault-password-file=.vault_pass.py