---
- hosts: game
  remote_user: arma
  vars:
    mods:
      - 450814997 # CBA_A3
      - 463939057 # ACE3
      - 583496184 # CUP Terrains - Core
      - 583544987 # CUP Terrains - Maps
      - 853743366 # CUP Terrains - CWA
      - 1375890861 # CUP ACE3 Compatibility Addon - Terrains
      - 843425103 # RHS AFRF
      - 843577117 # RHS USAF
      - 843593391 # RHS GREF
      - 843632231 # RHSSAF
      - 861133494 # JSRS Soundmod
      - 945476727 # JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support
      - 1180533757 # JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support
      - 1180534892 # JSRS SOUNDMOD - RHS GREF Mod Pack Sound Support
      - 1486541773 # JSRS SOUNDMOD - RHS SAF Mod Pack Support
      - 773131200 # ACE Compat - RHS Armed Forces of the Russian Federation
      - 773125288 # ACE Compat - RHS United States Armed Forces
      - 884966711 # ACE Compat - RHS: GREF
      - 1185836585 # ACE3 RHS Missile Guidance Сompatibility
      - 1136518526 # Ace Particles 3.12.5.40
      - 708250744 # ACEX
      - 723217262 # Achilles
      - 620260972 # ALiVE
      - 820924072 # BackpackOnChest
      - 767380317 # Blastcore Edited (standalone version)
      - 667953829 # BloodLust
      - 1435263885 # Diwako's ACE Ragdolling
      - 366425329 # FIR AWS(AirWeaponSystem)
      - 1227179728 # EA-18G Growler
      - 537154025 # F-14 Tomcat
      - 582478120 # F-15 Eagle
      - 366423278 # F-16 Fighting Falcon
      - 743099837 # FA-18 Super Hornet
      - 708278910 # Island Panthera
      - 779520435 # Multi-play Uniforms
      - 735566597 # Project OPFOR
      - 1207709270 # Tao Folding Map
      - 620019431 # task_force_radio
      - 643530417 # USS Nimitz
      - 721359761 # Vcom AI V3.1
      - 893328083 # 3CB BAF Equipment
      - 1661066023 # RKSL Studios: Attachments v3.00
      - 893339590 # 3CB BAF Weapons
      - 893349825 # 3CB BAF Vehicles
      - 893346105 # 3CB BAF Units
      - 1673456286 # 3CB Factions
      - 820994401 # FFAA MOD
      - 1515851169 # 3CB BAF Vehicles (RHS reskins)
      - 1515845502 # 3CB BAF Weapons (RHS ammo compatibility)
      - 1135543967 # 3CB BAF Vehicles (Servicing extension)
      - 1135541175 # 3CB BAF Units (RHS compatibility)
      - 1135539579 # 3CB BAF Units (ACE compatibility)
      - 1580089750 # Arma Containment Breach - SCP in ArmA III
      - 1600293139 # Project Lightning - F-35B Armaverse Version
      - 623475643 # 3den Enhanced
      - 1208939123 # Actionbuilder
      - 708278910 # Island Panthera
      - 836147398 # X-Cam-Taunus (Version 1.1)
      - 761349672 # CLA CLAFGHAN
      - 1598087521 # Summa
      - 714149065 # Isla Duala
      - 648775794 # Isla Abramia
      - 943001311 # Unsung Mod
      - 1547016606 # Advanced Breaching
      - 713709341 # Advanced Rappelling
      - 615007497 # Advanced Sling Loading
      - 639837898 # Advanced Towing
      - 1547762495 # Advanced Underbarrel
      - 730310357 # Advanced Urban Rappelling
      - 1378046829 # Advanced Weapon Mounting
      - 1569116504 # Advanced Zipline
      - 428181330 # Bornholm
      - 1509358862 # Caribbean Islands
      - 648172507 # G.O.S Al Rayak
      - 701535490 # G.O.S Dariyah
      - 855464203 # G.O.S Leskovets
      - 643744158 # G.O.S Kalu Khan
      - 693153082 # G.O.S Gunkizli
      - 937515516 # G.O.S N'Djenahoud
      - 520618345 # JBAD
      - 909547724 # LYTHIUM
      - 1329037386 # Sennoe
      - 1282716647 # Vidda|Legacy
      - 1446500688 # Angola Maps v1.3
      - 1281275340 # ARC Farkhar Valley
      - 1494115712 # Ihantala
      - 1494127420 # Ihantala Winter
      - 895405887 # Kulima island
      - 718649903 # Lingor/Dingor Island
      - 1724046234 # MAP Chernobyl FOR ARMA 3
      - 962932583 # MBG Buildings 3 (Arma2 Legacy)
      - 1527410521 # Rosche, Germany
      - 850767937 # SFP: Wamako
      - 1458210741 # Todt
      - 950966660 # Prei Khmaoch Luong | ព្រៃខ្មោចលង
      - 938375441 # Diaoyu Islands (Lighting Fixed)
      - 1692037148 # [16PF] Goose Green, Falklands
      - 777069287 # Uhao island
      - 1680471603 # Desert Battlegrounds
      - 1580089750 # Arma Containment Breach
      - 1763469776 # SCP 173
      - 333310405 # Enhanced Movement
    admins:
      - "76561198007051865" # Giggaflop
      - "76561198041702905" # Simpleton216
      - "76561197961945422" # Oddis
      - "76561198065986954" # Gamer
      - "76561198042250946" # Akkedude

  tasks:
    - name: Install Arma requirements
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - mailutils
          - postfix
          - curl
          - wget
          - file
          - bzip2
          - gzip
          - unzip
          - bsdmainutils
          - python
          - util-linux
          - ca-certificates
          - binutils
          - bc
          - jq
          - tmux
          - lib32gcc1
          - libstdc++6
          - libstdc++6:i386
          - git
          - rename
          - webhook

    - name: Download linuxgsm installer
      get_url:
        url: https://linuxgsm.sh
        dest: /home/arma/linuxgsm.sh
        mode: 0755

    - name: Install linuxgsm
      command: /home/arma/linuxgsm.sh arma3server
      args:
        chdir: /home/arma
        creates: /home/arma/arma3server

    - name: Install linuxgsm
      command: /home/arma/arma3server
      args:
        chdir: /home/arma
        creates: /home/arma/lgsm/config-lgsm/arma3server/

    - name: Set Arma Steam Username and Password
      template:
        src: steam.cfg
        dest: /home/arma/lgsm/config-lgsm/arma3server/common.cfg

    - name: Install Arma 3
      command: /home/arma/arma3server ai
      args:
        chdir: /home/arma
        creates: /home/arma/serverfiles
      register: result

    - name: Update Arma 3
      command: /home/arma/arma3server update
      when: result is skipped

    - name: Set the ssh key
      copy:
        src: deploy_key.pem
        dest: /home/arma/.ssh/id_rsa
        mode: 0600

    - file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/arma/serverfiles/.git-mpmissions"
        - "/home/arma/serverfiles/mpmissions"

    - name: Get Missions
      git:
        repo: git@github.com:dog-company/missions.git
        dest: /home/arma/serverfiles/mpmissions
        accept_hostkey: yes
        separate_git_dir: /home/arma/serverfiles/.git-mpmissions

    - name: Remove mission folders
      command: find /home/arma/serverfiles/mpmissions/ -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;

    - name: Template out modlist
      template:
        src: modlist.txt
        dest: /home/arma/modlist.txt

    - name: Create mod dir
      file:
        path: /home/arma/serverfiles/mods
        state: directory

    - name: Get checksum of mods directory
      stat:
        path: /home/arma/serverfiles/mods
        checksum_algorithm: sha256
      register: pre_mod_checksum

    - shell: ls -1 /home/arma/Steam/workshop/steamapps/workshop/content/107410/
      register: contents

    - file: path=/home/arma/Steam/workshop/steamapps/workshop/content/107410/{{ item }} state=absent
      with_items: contents.stdout_lines
      when: item not in mods

    - name: Get Mods
      command: "/home/arma/steamcmd/steamcmd.sh +runscript /home/arma/modlist.txt 2>&1"

    - name: Sync modfiles into place
      command: rsync -ry -a --link-dest=/home/arma/Steam/workshop/steamapps/workshop/content/107410/ --progress --delete /home/arma/Steam/workshop/steamapps/workshop/content/107410/ /home/arma/serverfiles/mods

    - name: Rename all files into lowercase
      command: find /home/arma/serverfiles/mods/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;

    - name: Get checksum of mods directory after updates
      stat:
        path: /home/arma/serverfiles/mods
        checksum_algorithm: sha256
      register: post_mod_checksum

    - debug:
        msg: "{{pre_mod_checksum.stat.checksum}} > {{post_mod_checksum.stat.checksum}}"
      when: pre_mod_checksum.stat.checksum is defined and post_mod_checksum.stat.checksum is defined

    - name: Redo bikey files for authorized mods
      command: find /home/arma/serverfiles/mods/ -type f -name "*.bikey" -exec cp {} /home/arma/serverfiles/keys \;

    - name: Configure the server
      template:
        src: server_settings.cfg
        dest: /home/arma/lgsm/config-lgsm/arma3server/arma3server.cfg

    - name: Create Player Profile
      file:
        path: "/home/arma/.local/share/Arma 3 - Other Profiles/Player/"
        state: directory

    - name: More configure the server
      template:
        src: server.Arma3Profile
        dest: "/home/arma/.local/share/Arma 3 - Other Profiles/Player/Player.Arma3Profile"

    - name: Create Player Profile
      file:
        path: "/home/arma/serverfiles/cfg/"
        state: directory

    - name: Extra more configure the server
      template:
        src: arma3server.server.cfg
        dest: /home/arma/serverfiles/cfg/arma3server.server.cfg

    - name: Start server on reboot
      cron:
        name: "Start server on reboot"
        special_time: reboot
        job: "/home/arma/arma3server start"
        user: arma

    - name: Check server hourly
      cron:
        name: "Check server hourly"
        special_time: hourly
        job: "/home/arma/arma3server monitor"
        user: arma

    - name: Start server
      shell:  /home/arma/arma3server start
      args:
        executable: /bin/bash
        chdir: /home/arma
      when: result is changed

    - name: Start server
      shell:  /home/arma/arma3server start
      args:
        executable: /bin/bash
        chdir: /home/arma
      when: result is skipped

    - name: Create missions update script
      copy:
        src: update_missions.sh
        dest: /home/arma/update_missions.sh
        mode: 0755

    - name: Create webhooks directory
      become: yes
      file:
        path: /etc/webhook
        state: directory

    - name: Configure webhooks
      become: yes
      template:
        src: webhooks.json
        dest: /etc/webhook/hooks.json
        mode: 0666

    - name: Create webhook Service
      become: yes
      copy:
        src: webhooks.service
        dest: /etc/systemd/system/webhooks.service
        mode: 0666

    - name: Start and enable webhooks service
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: webhooks.service

    - name: Create Arma 3 Service
      become: yes
      copy:
        src: systemd.service
        dest: /etc/systemd/system/arma3.service

    - name: Start and enable arma service
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: arma3.service

    - name: Enable Arma Service
      become: yes
      systemd:
        enabled: yes
        name: arma3.service

    - name: Enable Webhook Service
      become: yes
      systemd:
        enabled: yes
        name: webhooks.service